// Sample responses shown alongside the 402 challenge ("try before you buy"):
// an unpaid caller sees exactly the shape and kind of data a paid call returns.
// Values are illustrative snapshots, not live data.

export const PREVIEWS = {
  "POST /pdf": {
    output: "application/pdf (binary, A4, print-ready)",
    example_request: { template: "invoice", data: { number: "F-001", currency: "USD", tax_rate: 19, issuer: { name: "Acme LLC" }, client: { name: "Client Inc" }, items: [{ description: "Consulting", quantity: 2, unit_price: 150 }] } },
    templates: ["invoice", "report", "contract", "raw html"],
  },
  "GET /vat/rates": { code: "DE", country: "Germany", currency: "EUR", standard: 19, reduced: [7], vat_abbr: "MwSt", source: "European Commission TEDB" },
  "POST /vat/validate": { countryCode: "IE", vatNumber: "6388047V", valid: true, name: "GOOGLE IRELAND LIMITED", consultationDate: "2026-07-18T12:00:00Z", source: "European Commission VIES" },
  "POST /vat/price": { country: "DE", vat_name: "MwSt", rate_percent: 19, rate_type: "standard", net: 100, vat: 19, gross: 119 },
  "GET /fx/convert": { from: "USD", to: "EUR", amount: 100, rate: 0.8745, converted: 87.45, date: "2026-07-18", source: "European Central Bank reference rates" },
  "GET /fx/rates": { base: "USD", date: "2026-07-18", rates: { EUR: 0.8745, GBP: 0.7612, JPY: 148.2, "...": "30+ currencies" } },
  "GET /days/holidays": { country: "DE", year: 2026, total: 11, holidays: [{ date: "2026-01-01", name: "New Year's Day", nationwide: true }, { "...": "10 more" }] },
  "GET /days/business-days": { country: "US", from: "2026-08-31", days: 10, result_date: "2026-09-15", skipped_holidays: ["2026-09-07"] },
  "POST /validate/iban": { iban: "DE89 3704 0044 0532 0130 00", valid: true, country: "DE", check_digits: "89", formatted: "DE89 3704 0044 0532 0130 00" },
  "POST /validate/phone": { phone: "+56 9 6123 4567", valid: true, region: "CL", type: "mobile", e164: "+56961234567", international: "+56 9 6123 4567" },
  "POST /validate/tax-id": { country: "BR", id: "529.982.247-25", valid: true, type: "CPF", formatted: "529.982.247-25" },
  "GET /latam/indexacion": { unidad: "UVA", pais: "Argentina", valor: 2041.81, fecha: "2026-07-18", moneda: "ARS", monto: 100, equivalente_moneda_local: 204181 },
  "GET /latam/dolar-argentina": { oficial: { value_buy: 1451, value_sell: 1502 }, blue: { value_buy: 1497, value_sell: 1530 }, brecha_pct: 2.5, fuente: "Bluelytics" },
  "GET /latam/fx": {
    descripcion: "Tipos de cambio oficiales de LATAM contra USD, en una sola llamada",
    monedas: {
      CLP: { valor: 933.15, tipo: "dólar observado", fuente: "Banco Central de Chile" },
      ARS: { oficial: 1476.5, blue: 1513.5, brecha_pct: 2.5, fuente: "Bluelytics" },
      BRL: { valor: 5.0894, tipo: "PTAX venta", fuente: "BCB" },
      MXN: { valor: 18.61, tipo: "FIX oficial", fuente: "Banxico" },
      COP: { valor: 3262.58, tipo: "TRM legal", fuente: "datos.gov.co" },
      PEN: { valor: 3.396, tipo: "SBS venta", fuente: "BCRP" },
    },
    completo: true,
  },
  "GET /br/indices": { pais: "Brasil", indices: { selic: { valor: 14.25, unidad: "% a.a." }, cdi: { valor: 14.15, unidad: "% a.a." }, ipca: { valor: 0.26, unidad: "% mensual" }, ptax: { valor: 5.0894, unidad: "BRL por USD" } }, fuente: "Banco Central do Brasil (SGS)" },
  "GET /br/cep": { cep: "01310-100", found: true, calle: "Avenida Paulista", barrio: "Bela Vista", ciudad: "São Paulo", estado: "SP", fuente: "ViaCEP" },
  "GET /ar/indices": { pais: "Argentina", inflacion_mensual: { valor: 1.9, mes: "2026-06" }, inflacion_interanual_pct: 27.4, riesgo_pais: { valor: 419, unidad: "puntos básicos" }, fuente: "INDEC/BCRA vía ArgentinaDatos" },
  "GET /co/trm": { pais: "Colombia", indicador: "TRM", valor: 3262.58, moneda: "COP por USD", vigente_desde: "2026-07-18", fuente: "Superintendencia Financiera" },
  "GET /pe/tipo-cambio": { pais: "Perú", venta: 3.396, compra: 3.389, moneda: "PEN por USD", fuente: "BCRP" },
  "GET /mx/indicadores": { pais: "México", dolar_fix: { valor: 18.61, unidad: "MXN por USD" }, tiie_28d: { valor: 7.75, unidad: "% anual" }, fuente: "Banco de México (SIE)" },
  "GET /cl/reajuste": { desde: "2025-01", hasta: "2025-06", meses_compuestos: 5, variacion_pct: 1.87, factor: 1.0187, monto: 500000, monto_reajustado: 509350, fuente: "INE Chile vía mindicador.cl" },
  "POST /qr": { output: "image/png or image/svg+xml (binary)", example_request: { data: "https://toolrail.dev", format: "png", size: 512 } },
  "GET /cl/indicadores": { indicador: "uf", valor: 40844.79, fecha: "2026-07-17", fuente: "mindicador.cl (Banco Central de Chile)" },
  "GET /cl/uf": { direccion: "uf-clp", monto: 50, resultado: 2042239.5, valor_uf: 40844.79, fecha: "2026-07-17" },
  "GET /cl/dias-habiles": { desde: "2026-09-14", plazo: 10, tipo: "administrativo", fecha_resultado: "2026-09-29", feriados_saltados: ["2026-09-18"] },
  "GET /cl/feriados": { year: 2026, total: 16, feriados: [{ date: "2026-09-18", name: "Independencia Nacional" }, { "...": "15 more" }] },
  "POST /cl/rut": { rut: "12.345.678-5", valid: true, formatted: "12.345.678-5" },
  "POST /cl/sueldo-liquido": { bruto: 1500000, descuentos: { afp: 158700, salud: 105000, seguro_cesantia: 9000, impuesto_unico: 22000 }, liquido: 1205300, disclaimer: "Cálculo referencial" },
  "GET /cl/farmacias-turno": { comuna: "VALPARAISO", total: 2, farmacias: [{ nombre: "FARMACIA EJEMPLO", direccion: "AV. ARGENTINA 100", apertura: "20:00", cierre: "08:30" }] },
  "GET /guia/pdf": { output: "application/pdf — 'Build your own x402 API' (12 chapters + printable checklist). Available in es/en/pt via ?lang=", free_web_edition: "https://toolrail.dev/guia", languages: ["es", "en", "pt"] },
};
